micronaut:
  application:
    name: webservices_labb2

#MongoDB:
mongodb:
  uri: mongodb://${MONGO_USERNAME:mongoadmin}:${MONGO_PASSWORD:secret}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}

#Database:
db1:
  name: 'mongo'
  collection: 'soda'

db2:
  name: 'mongo'
  collection: 'fish'
